version: '3'

services:
   db:
      image: mongo:5
      restart: always
      ports:
       - 8081:8081
      environment:
       MONGODB_DATABASE: project-x-api
      volumes:
       - ./mongo:/data/db